routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'auth'], function() {
	Route::group(['prefix' => 'admin'], function () {
		Route::group(['middleware' => 'admin:admin'], function() {
			Route::get('sms', 'SmsController@index')->name('sms.list');
			Route::get('sms/birthdate', 'SmsController@setBirthdateText')->name('sms.birthdate');
			Route::post('sms/birthdate', 'SmsController@setBirthdateText');
			Route::get('sms/create', 'SmsController@create')->name('sms.create');
			Route::post('sms/create', 'SmsController@create');
			Route::get('sms/{smsSender}', 'SmsController@create')->name('sms.show');
			Route::get('card/{card}/sms', 'CardController@sms')->name('card.sms');
			Route::post('card/{card}/sms', 'CardController@sms');
			Route::get('vip/{vip}/sms', 'VipController@checks')->name('vip.sms');
			Route::post('vip/{vip}/sms', 'VipController@checks');
			Route::resources([
				'user' => 'UserController'
			]);
		});
		Route::group(['middleware' => 'admin:manager'], function() {
			Route::get('card/{card}/checks', 'CardController@checks')->name('card.checks');
			Route::get('card/{card}/checks/add', 'CardController@checksAdd')->name('card.checks.add');
			Route::post('card/{card}/checks/add', 'CardController@checksAdd');
			//Route::get('card/migrate', 'CardController@migrate');
			//Route::post('card/migrate', 'CardController@migrate');

			Route::resources([
				'check' => 'CheckController',
				'card' => 'CardController',
				'vip' => 'VipController'
			]);
		});
	});
});

app/Check.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Check extends Model
{
    //
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'sum', 'initial', 'buyed_on', 'is_discount'
    ];

    /**
     *
     * Eloquent Relationships
     *
     *
    */
    //Cards
    public function card()
    {
        return $this->belongsTo('App\Card');
    }

    /**
     *
     * Mutators
     *
     *
    */
    //Summ with demitial
    public function getSumAttribute($value)
    {
        return $value/100;
    }

    public function scopeFilter($query, $filter)
    {
        if (isset($filter['date_start']) && $filter['date_start'] && isset($filter['date_end']) && $filter['date_end'])
        {
            $filter['date_start'] = $filter['date_start']. ' 00:00:00';
            $filter['date_end'] = $filter['date_end']. ' 00:00:00';
            $query->where('created_at', '>=', Carbon::createFromFormat("d/m/Y H:i:s", $filter['date_start']));
            $query->where('created_at', '<=', Carbon::createFromFormat("d/m/Y H:i:s", $filter['date_end'])->addDay());            
        }
        elseif (isset($filter['date_start']) && $filter['date_start'])
        {
            $filter['date_start'] = $filter['date_start']. ' 00:00:00';
            $query->where('created_at', '>=', Carbon::createFromFormat("d/m/Y H:i:s", $filter['date_start']));
            $query->where('created_at', '<=', Carbon::createFromFormat("d/m/Y H:i:s", $filter['date_start'])->addDay());
        }

        return $query;
    }
}

app/Http/Controllers/CheckController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Check;

class CheckController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $checks = new Check;
        $checks = $checks->where('initial', '!=', true);
        if ($request->set_filter)
        {

            $checks = $checks->filter($request->all())->paginate(20);
        }
        else
        {
            $checks = $checks->paginate(20);
        }
        return view('admin.check.list', ['checks' => $checks]);
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Check $check)
    {
        //
        $card = $check->card;
        $check->delete();
        $card->resumPercent();
        return redirect()->back()->with('status', 'Чек удален');
    }
}

resources/views/admin/check/list.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    
    <div class="col-md-8 col-md-offset-2">
        <form method="get" enctype="multipart/form-data">
            <input type="hidden" name="set_filter" value="y">
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label>Дата</label>
                    <input type="text" class="form-control" name="date_start" placeholder="с" id="datetimepicker1" value="{{request()->input('date_start')}}" autocomplete="off">
                </div>
                <div class="form-group col-md-3">
                    <label>&nbsp;</label>
                    <input type="text" class="form-control" name="date_end" placeholder="по" id="datetimepicker2" value="{{request()->input('date_end')}}" autocomplete="off">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label>&nbsp;</label>
                    <button type="submit" class="btn btn-primary form-control" name="search" value="y">Применить</button>
                </div>
                <div class="form-group col-md-3">
                    <label>&nbsp;</label>
                    <a href="/admin/check" class="btn btn-info form-control">Очистить</a>
                </div>
            </div>
        </form>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Сумма</th>
                    <th scope="col">Дата</th>
                    <th scope="col">Покупатель</th>
                    <th scope="col">Из файла</th>
                    <th scope="col">Скидка</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($checks as $check)
                <tr>
                    <th scope="row">{{$check->id}}</th>
                    <td>{{$check->sum}}</td>
                    <td>{{$check->buyed_on}}</td>
                    <td>{{$check->card->name}}</td>
                    <td>
                        @if ($check->initial)
                        Да
                        @endif
                    </td>
                    <td>
                        @if ($check->is_discount)
                        Да
                        @endif
                    </td>
                    <td>
                        @if (!$check->is_discount && !$check->initial)
                        <a href="#" onclick="event.preventDefault();
                            if(confirm('Действительно удалить?'))
                                document.getElementById('delete-check-manager-form-{{$check->id}}').submit();">Удалить</a>
                            <form action="{{ route('check.destroy', ['check' => $check]) }}" method="POST" id="delete-check-manager-form-{{$check->id}}">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                            </form>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
        {{ $checks->links() }}
    </div>
</div>
@endsection

@section('adittional-scripts')
<script type="text/javascript">
    $(function () {
        $('#datetimepicker1').datetimepicker({
            format: 'DD/MM/YYYY'
        });
        $('#datetimepicker2').datetimepicker({
            format: 'DD/MM/YYYY'
        });
    });
</script>
@endsection