routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index');

Route::group(['middleware' => 'auth'], function() {
	Route::group(['prefix' => 'admin'], function () {
		Route::group(['middleware' => 'admin:admin'], function() {
			Route::get('sms', 'SmsController@index')->name('sms.list');
			Route::get('sms/birthdate', 'SmsController@setBirthdateText')->name('sms.birthdate');
			Route::post('sms/birthdate', 'SmsController@setBirthdateText');
			Route::get('sms/create', 'SmsController@create')->name('sms.create');
			Route::post('sms/create', 'SmsController@create');
			Route::get('sms/{smsSender}', 'SmsController@create')->name('sms.show');
			Route::get('card/{card}/sms', 'CardController@sms')->name('card.sms');
			Route::post('card/{card}/sms', 'CardController@sms');
			Route::get('vip/{vip}/sms', 'VipController@checks')->name('vip.sms');
			Route::post('vip/{vip}/sms', 'VipController@checks');
			Route::resources([
				'user' => 'UserController'
			]);
		});
		Route::group(['middleware' => 'admin:manager'], function() {
			Route::get('card/{card}/checks', 'CardController@checks')->name('card.checks');
			Route::get('card/{card}/checks/add', 'CardController@checksAdd')->name('card.checks.add');
			Route::post('card/{card}/checks/add', 'CardController@checksAdd');
			//Route::get('card/migrate', 'CardController@migrate');
			//Route::post('card/migrate', 'CardController@migrate');

			Route::resources([
				'check' => 'CheckController',
				'card' => 'CardController',
				'vip' => 'VipController'
			]);
		});
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     *
     * Eloquent Relationships
     *
     *
    */
    public function smsSender()
    {
        return $this->hasMany('App\SmsSender');
    }

    public function sms()
    {
        return $this->hasMany('App\Sms');
    }

    public function checkRole($role)
    {
        if ($this->id == 2)
        {
            return true;
        }
        if ($role == 'admin')
        {
            if ($this->is_admin == 2)
            {
                return true;
            }
            return false;
        }
        if ($role == 'manager')
        {
            if ($this->is_admin >= 1)
            {
                return true;
            }
            return false;
        }
        return false;
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.list', ['users' => User::all()]);
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        if ($request->isMethod('put'))
        {
            $user->update($request->only(['is_admin']));
            return back()->with('status', 'Изменения сохранены!');
        }
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
        $user->delete();
        return redirect()->back()->with('status', 'Пользователь удален');
    }
}

resources/views/admin/users/create.blade.php
create

resources/views/admin/users/list.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    
    <div class="col-md-8 col-md-offset-2">
        
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Имя</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Администратор</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                <tr>
                    <th scope="row">{{$user->id}}</th>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>
                        @if ($user->checkRole('admin'))
                            Администратор<br/>
                            <a href="#" onclick="event.preventDefault();
                            if(confirm('Действительно удалить?'))
                                document.getElementById('edit-card-form-{{$user->id}}').submit();">Удалить из менеджеров и админов</a>
                            <form action="{{ route('user.update', ['user' => $user]) }}" method="POST" id="edit-card-form-{{$user->id}}">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <input id="is_admin-{{$user->id}}" type="hidden" class="form-control" name="is_admin" value="0">
                            </form>
                            <a href="#" onclick="event.preventDefault();
                                document.getElementById('edit-card-manager-form-{{$user->id}}').submit();">Сделать менеджером</a>
                            <form action="{{ route('user.update', ['user' => $user]) }}" method="POST" id="edit-card-manager-form-{{$user->id}}">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <input id="is_admin-{{$user->id}}" type="hidden" class="form-control" name="is_admin" value="1">
                            </form>
                        @elseif($user->checkRole('manager'))
                            Менеджер<br/><a href="#" onclick="event.preventDefault();
                                document.getElementById('edit-card-form-{{$user->id}}').submit();">Сделать админом</a>
                            <form action="{{ route('user.update', ['user' => $user]) }}" method="POST" id="edit-card-form-{{$user->id}}">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <input id="is_admin-{{$user->id}}" type="hidden" class="form-control" name="is_admin" value="2">
                            </form>
                            <a href="#" onclick="event.preventDefault();
                            if(confirm('Действительно удалить?'))
                                document.getElementById('edit-card-manager-form-{{$user->id}}').submit();">Удалить из менеджеров</a>
                            <form action="{{ route('user.update', ['user' => $user]) }}" method="POST" id="edit-card-manager-form-{{$user->id}}">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <input id="is_admin-{{$user->id}}" type="hidden" class="form-control" name="is_admin" value="0">
                            </form>
                        @else
                            <a href="#" onclick="event.preventDefault();
                                document.getElementById('edit-card-form-{{$user->id}}').submit();">Сделать админом</a>
                            <form action="{{ route('user.update', ['user' => $user]) }}" method="POST" id="edit-card-form-{{$user->id}}">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <input id="is_admin-{{$user->id}}" type="hidden" class="form-control" name="is_admin" value="2">
                            </form>
                            <a href="#" onclick="event.preventDefault();
                                document.getElementById('edit-card-manager-form-{{$user->id}}').submit();">Сделать Менеджером</a>
                            <form action="{{ route('user.update', ['user' => $user]) }}" method="POST" id="edit-card-manager-form-{{$user->id}}">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <input id="is_admin-{{$user->id}}" type="hidden" class="form-control" name="is_admin" value="1">
                            </form>
                        @endif
                    </td>
                    <td>
                        @if (Auth::user()->id != $user->id)
                        <a href="#" data-original-title="Delete this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger" onclick="event.preventDefault();
                                                if(confirm('Действительно удалить?'))
                                                     document.getElementById('delete-card-form-{{$user->id}}').submit();"><i class="glyphicon glyphicon-trash"></i></a>
                        <form action="{{route('user.destroy', ['user' => $user])}}" method="POST" id="delete-card-form-{{$user->id}}">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                        </form>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection